version: '3.8'

services:
  api:
    build: .
    container_name: server_management_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./ssl:/app/ssl
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: server_management_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped